name: staging merge
on:
  push:
    branches:
    - production
jobs:
  staging-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: production -> staging
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: production
          target_branch: staging
          github_token: ${{ github.token }}
