name: staging merge
on:
  push:
    branches:
    - production
jobs:
  staging-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: production -> staging
        uses: Yuji-Kuroko/merge-branch@debug
        with:
          type: now
          head_to_merge: production
          target_branch: staging
          github_token: ${{ github.token }}
